# Generated by Django 4.0.4 on 2022-04-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_cursus_student_comments_student_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursus',
            options={'verbose_name_plural': 'Cursus'},
        ),
    ]
