# Generated by Django 3.1.5 on 2022-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_alter_cursus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default='1980-01-01', verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
